# Generated by Django 4.0.6 on 2022-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
