# Generated by Django 4.0.6 on 2022-07-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_salesitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='status',
        ),
    ]
